# Generated by Django 4.0.3 on 2022-03-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntropyCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=100)),
                ('csv_file', models.FileField(blank=True, upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
