# Generated by Django 4.0.3 on 2022-03-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_entropycalc_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='entropycalc',
            name='output',
            field=models.FileField(blank=True, upload_to='output_csv/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='entropycalc',
            name='csv_file',
            field=models.FileField(blank=True, upload_to='input_csv/%Y/%m/%d'),
        ),
    ]
