# Generated by Django 4.0.3 on 2022-03-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_entropycalc_output_alter_entropycalc_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entropycalc',
            name='output',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/output/output.csv', upload_to='output_csv/%Y/%m/%d'),
        ),
    ]
