# Generated by Django 4.0.3 on 2022-03-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_entropycalc_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entropycalc',
            name='output',
            field=models.FileField(blank=True, default='C:\\Users\\Mohit\\Desktop\\2022\\work\\entropy-calc\\media\\output.csv', upload_to='output_csv/%Y/%m/%d'),
        ),
    ]
