# Generated by Django 4.0.3 on 2022-03-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_alter_entropycalc_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='entropycalc',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
