# Generated by Django 4.0.3 on 2022-03-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_remove_entropycalc_output_remove_entropycalc_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='entropycalc',
            name='CALCULATE',
            field=models.CharField(choices=[('shannon', 'Shannon'), ('tsallis', 'Tsallis')], default='shannon', max_length=100),
        ),
    ]
