# Generated by Django 4.0.3 on 2022-03-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_entropycalc_calculate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entropycalc',
            old_name='CALCULATE',
            new_name='calculate',
        ),
    ]
